site_name: Vozes em Rede
site_dir: public

theme:
  name: material
  language: pt-BR
  logo: assets/logos/logo_simbolo.png
  favicon: 
  icon:
    repo: fontawesome/brands/github
  
  features:
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.top
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro


  hide:
    -

  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk

  plugins:
    - glightbox
    - search:
        lang: pt-BR

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/styles.css

nav:
  - Sobre: index.md
  - Produto:
    - Visão do Produto: produto/visao_do_produto.md
    - Mapeamento de Dados: produto/mapeamento_de_dados.md
    - Requisitos do Produto: produto/requisitos_do_produto.md
  - Machine Learning:
    - Requisitos de ML: ml/requisitos_de_ml.md
    - ML Canvas: ml/ml_canvas.md
  - Histórias de Usuário:
    - Lista de Histórias: historias_de_usuario/us_list.md
    - Aceitação e priorização: historias_de_usuario/criterios_de_aceitacao.md
    - MVP e Cronograma: historias_de_usuario/mvp.md
  - Engenharia de Dados:
    - Coleta e Armazenamento: engenharia_de_dados/coleta_e_armazenamento.md
    - Amostragem e Rotulação: engenharia_de_dados/amostragem_e_rotulacao.md
    - Feature Engineering: engenharia_de_dados/feature_engineering.md
    - Dados de Treinamento e Teste: engenharia_de_dados/dados_treinamento_teste.md

# Para novas entregas, adicione novas seções abaixo seguindo o padrão acima.

          

